### ISSUE TITLE
'Tensor' object has no attribute '_pad_token_tensor'

### ISSUE THREAD

**Issue by seyedaed** [smthemex/ComfyUI_ParlerTTS#11]
Hey everyone not sure if this is an issue with the code or my configuration.  But, I tried running this and this is the error I received.  Any advice or assistance will be appreciated. 

![image](https://github.com/user-attachments/assets/a46644f7-8b08-4bba-84ee-a02506f3d5d8)

FETCH DATA from: C:\Users\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
Config of the text_encoder: <class 'transformers.models.t5.modeling_t5.T5EncoderModel'> is overwritten by shared text_encoder config: T5Config {
  "_name_or_path": "google/flan-t5-large",
  "architectures": [
    "T5ForConditionalGeneration"
  ],
  "classifier_dropout": 0.0,
  "d_ff": 2816,
  "d_kv": 64,
  "d_model": 1024,
  "decoder_start_token_id": 0,
  "dense_act_fn": "gelu_new",
  "dropout_rate": 0.1,
  "eos_token_id": 1,
  "feed_forward_proj": "gated-gelu",
  "initializer_factor": 1.0,
  "is_encoder_decoder": true,
  "is_gated_act": true,
  "layer_norm_epsilon": 1e-06,
  "model_type": "t5",
  "n_positions": 512,
  "num_decoder_layers": 24,
  "num_heads": 16,
  "num_layers": 24,
  "output_past": true,
  "pad_token_id": 0,
  "relative_attention_max_distance": 128,
  "relative_attention_num_buckets": 32,
  "tie_word_embeddings": false,
  "transformers_version": "4.47.1",
  "use_cache": true,
  "vocab_size": 32128
}

Config of the audio_encoder: <class 'ComfyUI_ParlerTTS.parler_tts.dac_wrapper.modeling_dac.DACModel'> is overwritten by shared audio_encoder config: DACConfig {
  "_name_or_path": "parler-tts/dac_44khZ_8kbps",
  "architectures": [
    "DACModel"
  ],
  "codebook_size": 1024,
  "frame_rate": 86,
  "latent_dim": 1024,
  "model_bitrate": 8,
  "model_type": "dac_on_the_hub",
  "num_codebooks": 9,
  "sampling_rate": 44100,
  "torch_dtype": "float32",
  "transformers_version": "4.47.1"
}

Config of the decoder: <class 'ComfyUI_ParlerTTS.parler_tts.modeling_parler_tts.ParlerTTSForCausalLM'> is overwritten by shared decoder config: ParlerTTSDecoderConfig {
  "_name_or_path": "/fsx/yoach/tmp/artefacts/parler-tts-mini/decoder",
  "activation_dropout": 0.0,
  "activation_function": "gelu",
  "add_cross_attention": true,
  "architectures": [
    "ParlerTTSForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 1025,
  "codebook_weights": null,
  "cross_attention_implementation_strategy": null,
  "dropout": 0.1,
  "eos_token_id": 1024,
  "ffn_dim": 4096,
  "hidden_size": 1024,
  "initializer_factor": 0.02,
  "is_decoder": true,
  "layerdrop": 0.0,
  "max_position_embeddings": 4096,
  "model_type": "parler_tts_decoder",
  "num_attention_heads": 16,
  "num_codebooks": 9,
  "num_cross_attention_key_value_heads": 16,
  "num_hidden_layers": 24,
  "num_key_value_heads": 16,
  "pad_token_id": 1024,
  "rope_embeddings": false,
  "rope_theta": 10000.0,
  "scale_embedding": false,
  "tie_word_embeddings": false,
  "torch_dtype": "float32",
  "transformers_version": "4.47.1",
  "use_cache": true,
  "use_fused_lm_heads": false,
  "vocab_size": 1088
}

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
!!! Exception during processing !!! 'Tensor' object has no attribute '_pad_token_tensor'
Traceback (most recent call last):
  File "C:\Users\ComfyUI\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ComfyUI\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ComfyUI\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\ComfyUI\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ParlerTTS\parler_tts_node.py", line 70, in prompt2audio
    generation = model.generate(input_ids=input_ids, prompt_input_ids=prompt_input_ids)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ComfyUI\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ParlerTTS\parler_tts\modeling_parler_tts.py", line 3422, in generate
    model_kwargs["attention_mask"] = self._prepare_attention_mask_for_generation(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ComfyUI\python_embeded\Lib\site-packages\transformers\generation\utils.py", line 585, in _prepare_attention_mask_for_generation
    pad_token_id = generation_config._pad_token_tensor
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Tensor' object has no attribute '_pad_token_tensor'

**Comment by smthemex** [comment]
try update your transformers ，like: pip install -U transformers

**Comment by seyedaed** [comment]
Thanks for the quick reply. I tried to update the transformers but they are up to date and same error.  Here is some additional system info in case it helps.

```
## System Information
- **ComfyUI Version:** v0.3.9-18-gbc6dac4
- **Arguments:** ComfyUI\main.py --windows-standalone-build --lowvram --cuda-device 0
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.1+cu124
## Devices

**Comment by seyedaed** [comment]
When googling I came across a similar issue for indic-parler-tts and am wondering if maybe its related somehow? 

https://huggingface.co/ai4bharat/indic-parler-tts/discussions/2

**Comment by seyedaed** [comment]
Hey I got a fix for this related to the above.  It seems it wants the  attention mask added now.  Idk if this is a new update on something or what but this is the fix thanks in part to AI.  In paerler_tts_node.py I updated this the prompt2audio function and it works now. 

Replaced this:

    def prompt2audio(self, model, prompt, description):
        
        tokenizer=model.get("tokenizer")
        model = model.get("model")
        model.to(device)
        
        input_ids = tokenizer(description, return_tensors="pt").input_ids.to(device)
        prompt_input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to(device)
        
        generation = model.generate(input_ids=input_ids, prompt_input_ids=prompt_input_ids)
        audio_arr = generation.cpu().numpy().squeeze()
        waveform=torch.from_numpy(audio_arr).unsqueeze(0)
        
        audio= {"waveform": waveform.unsqueeze(0), "sample_rate": model.config.sampling_rate}
        return (audio,)
   

With:  




   def prompt2audio(self, model, prompt, description):
        
        tokenizer=model.get("tokenizer")
        model = model.get("model")
        model.to(device)
        
        # Tokenize and create attention masks
        description_encoding = tokenizer(description, return_tensors="pt", padding=True, truncation=True)
        prompt_encoding = tokenizer(prompt, return_tensors="pt", padding=True, truncation=True)
        
        input_ids = description_encoding.input_ids.to(device)
        prompt_input_ids = prompt_encoding.input_ids.to(device)
        attention_mask = description_encoding.attention_mask.to(device)


        generation = model.generate(
            input_ids=input_ids,
            prompt_input_ids=prompt_input_ids,
            attention_mask=attention_mask
        )


        audio_arr = generation.cpu().numpy().squeeze()
        waveform=torch.from_numpy(audio_arr).unsqueeze(0)
        
        audio= {"waveform": waveform.unsqueeze(0), "sample_rate": model.config.sampling_rate}
        return (audio,)


Anyway not sure if this will work with other builds but I hope this helps in some way and appreciate both your assistance and the great node you created.

**Comment by smthemex** [comment]
Yeah, when use old codes ,will get a warning ,but it's still works. update attention-mask ,it 's work too. I will update it soon ,thanks for your codes..
